services:
  - type: web_service
    name: yayra-nail-shop
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    branch: master
    autoDeploy: true
    buildCommand: ''
    startCommand: ''
